version: "3.8"

services:
  ignite-node-1:
    image: apacheignite/ignite:latest
    container_name: ignite-node-1
    ports:
      - "10800:10800"  # Thin client bağlantı noktası
      - "47100:47100"  # İç iletişim portu
      - "47500:47500"  # Keşif portu
      - "49112:49112"  # Yardımcı port
    environment:
      - OPTION_LIBS=ignite-rest-http,ignite-indexing
      - CONFIG_URI=/ignite-config.xml
      - IGNITE_WORK_DIR=/storage
      - JAVA_OPTS=-DIGNITE_PEER_CLASS_LOADING=true
    volumes:
      - ignite-storage:/storage
      - ./ignite-config.xml:/ignite-config.xml  # Özel Ignite konfigürasyonu
    networks:
      - ignite-cluster

  ignite-node-2:
    image: apacheignite/ignite:latest
    container_name: ignite-node-2
    depends_on:
      - ignite-node-1
    environment:
      - OPTION_LIBS=ignite-rest-http,ignite-indexing
      - CONFIG_URI=/ignite-config.xml
      - IGNITE_WORK_DIR=/storage
      - JAVA_OPTS=-DIGNITE_PEER_CLASS_LOADING=true
    volumes:
      - ignite-storage:/storage
      - ./ignite-config.xml:/ignite-config.xml
    networks:
      - ignite-cluster

  ignite-node-3:
    image: apacheignite/ignite:latest
    container_name: ignite-node-3
    depends_on:
      - ignite-node-1
    environment:
      - OPTION_LIBS=ignite-rest-http,ignite-indexing
      - CONFIG_URI=/ignite-config.xml
      - IGNITE_WORK_DIR=/storage
      - JAVA_OPTS=-DIGNITE_PEER_CLASS_LOADING=true
    volumes:
      - ignite-storage:/storage
      - ./ignite-config.xml:/ignite-config.xml
    networks:
      - ignite-cluster


  hazelcast-node-1:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast-node-1
    environment:
      - HZ_CLUSTERNAME=hazelcast-cluster
    networks:
      - hazelcast-cluster

  hazelcast-node-2:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast-node-2
    depends_on:
      - hazelcast-node-1
    environment:
      - HZ_CLUSTERNAME=hazelcast-cluster
    networks:
      - hazelcast-cluster

  hazelcast-node-3:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast-node-3
    depends_on:
      - hazelcast-node-1
    environment:
      - HZ_CLUSTERNAME=hazelcast-cluster
    networks:
      - hazelcast-cluster

  hazelcast-management-center:
    image: hazelcast/management-center:latest
    container_name: hazelcast-mc
    depends_on:
      - hazelcast-node-1
    ports:
      - "8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=hazelcast-cluster
    networks:
      - hazelcast-cluster

volumes:
 ignite-storage:

networks:
  ignite-cluster:
    driver: bridge
  hazelcast-cluster:
    driver: bridge
